FROM python:3.13-alpine

WORKDIR /usr/local/app


COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
 
COPY . .

RUN uv sync --locked



CMD ["uv", "run", "fastapi", "run", "main.py", "--host", "0.0.0.0", "--port", "8000"]

