[project]
name = "projct"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "“youssefdadda99-create”", email = "dadda.youssef@bcg.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "pandas>=3.0.6",
]

[project.scripts]
projct = "projct:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
