name : build-image-on-push
on : [push]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : checkout repository

        uses: actions/checkout@v4

      - name : docker buildx setup
      
        uses: docker/setup-buildx-action@v3

      - name : build image 

        uses : docker/build-push-action@v6

        with:
          context : .
          file: ./DOCKERFILE
          push: false 